### ISSUE TITLE
help

### ISSUE THREAD

**Issue by EziiPz** [shamhi/MemeFiBot#1]
(venv) C:\Users\MemeFiBot>pip install pydantic
Requirement already satisfied: pydantic in c:\users\memefibot\venv\lib\site-packages (2.6.4)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\memefibot\venv\lib\site-packages (from pydantic) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in c:\users\memefibot\venv\lib\site-packages (from pydantic) (2.16.3)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\memefibot\venv\lib\site-packages (from pydantic) (4.10.0)

(venv) C:\Users\iloli\MemeFiBot>python main.py
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "C:\Users\MemeFiBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\MemeFiBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\MemeFiBot\bot\utils\launcher.py", line 8, in <module>
    from bot.config import settings
  File "C:\Users\MemeFiBot\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\MemeFiBot\bot\config\config.py", line 1, in <module>
    from pydantic_settings import BaseSettings, SettingsConfigDict
  File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_settings\__init__.py", line 1, in <module>
    from .main import BaseSettings, SettingsConfigDict
  File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_settings\main.py", line 7, in <module>
    from pydantic._internal._config import config_keys
  File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic\_internal\_config.py", line 12, in <module>
    from pydantic_core import core_schema
  File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

**Comment by wahyuda110** [comment]
same , u solved bro? tell me pls

**Comment by shamhi** [comment]
which python version do you use?

**Comment by wahyuda110** [comment]
python 3 on linux

**Comment by shamhi** [comment]
which version 3.???

**Comment by wahyuda110** [comment]
python-3.12.2

**Comment by shamhi** [comment]
you need python 3.10 or 3.11

**Comment by EziiPz** [comment]
i trying use 3.10 and same error

**Comment by EziiPz** [comment]
i use 3.11 and get same error again

**Comment by wahyuda110** [comment]
2024-03-31 09:21:15 | INFO     | 58 - Detected 0 sessions
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MemeFiBot-main\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\MemeFiBot-main\main.py", line 8, in main
    await process()
  File "C:\Users\Administrator\Desktop\MemeFiBot-main\bot\utils\launcher.py", line 63, in process
    print(start_text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 4-9: character maps to <undefined>


new error

**Comment by shamhi** [comment]
> (venv) C:\Users\MemeFiBot>pip install pydantic Requirement already satisfied: pydantic in c:\users\memefibot\venv\lib\site-packages (2.6.4) Requirement already satisfied: annotated-types>=0.4.0 in c:\users\memefibot\venv\lib\site-packages (from pydantic) (0.6.0) Requirement already satisfied: pydantic-core==2.16.3 in c:\users\memefibot\venv\lib\site-packages (from pydantic) (2.16.3) Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\memefibot\venv\lib\site-packages (from pydantic) (4.10.0)
> 
> (venv) C:\Users\iloli\MemeFiBot>python main.py TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups Traceback (most recent call last): File "C:\Users\MemeFiBot\main.py", line 4, in from bot.utils.launcher import process File "C:\Users\MemeFiBot\bot\utils__init__.py", line 2, in from . import launcher File "C:\Users\MemeFiBot\bot\utils\launcher.py", line 8, in from bot.config import settings File "C:\Users\MemeFiBot\bot\config__init__.py", line 1, in from .config import settings File "C:\Users\MemeFiBot\bot\config\config.py", line 1, in from pydantic_settings import BaseSettings, SettingsConfigDict File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_settings__init__.py", line 1, in from .main import BaseSettings, SettingsConfigDict File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_settings\main.py", line 7, in from pydantic._internal._config import config_keys File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_internal_config.py", line 12, in from pydantic_core import core_schema File "C:\Users\MemeFiBot\venv\Lib\site-packages\pydantic_core__init__.py", line 6, in from ._pydantic_core import ( ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

https://stackoverflow.com/questions/76650856/no-module-named-pydantic-core-pydantic-core-in-aws-lambda-though-library-is-i

**Comment by shamhi** [comment]
> 2024-03-31 09:21:15 | INFO | 58 - Detected 0 sessions Traceback (most recent call last): File "C:\Users\Administrator\Desktop\MemeFiBot-main\main.py", line 13, in asyncio.run(main()) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete return future.result() File "C:\Users\Administrator\Desktop\MemeFiBot-main\main.py", line 8, in main await process() File "C:\Users\Administrator\Desktop\MemeFiBot-main\bot\utils\launcher.py", line 63, in process print(start_text) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode characters in position 4-9: character maps to
> 
> new error

try to put this code in bot/utils/launcher.py
```
import sys
sys.stdout.reconfigure(encoding='utf-8')
```

**Comment by wahyuda110** [comment]
solved thanks u , solved using python 3.10 , and .env

**Comment by EziiPz** [comment]
> solved thanks u , solved using python 3.10 , and .env
send link python u using pls

**Comment by EziiPz** [comment]
@wahyuda110 tutor dong gan klo boleh minta telenya buat contact di gw error mulu

**Comment by wahyuda110** [comment]
> @wahyuda110 tutor dong gan klo boleh minta telenya buat contact di gw error mulu

kayak nya salah setting di bagian .env nya punya mu bang

```
API_ID=xxxxx
API_HASH=xxxxx

MIN_AVAILABLE_ENERGY=
SLEEP_BY_MIN_ENERGY=

AUTO_UPGRADE_TAP=
MAX_TAP_LEVEL=
AUTO_UPGRADE_ENERGY=
MAX_ENERGY_LEVEL=
AUTO_UPGRADE_CHARGE=
MAX_CHARGE_LEVEL=

APPLY_DAILY_ENERGY=
APPLY_DAILY_TURBO=

RANDOM_TAPS_COUNT=[50, 200]
SLEEP_BETWEEN_TAP=
```
coba set kyk gitu buat api_id hash_id nya ambil disini login pakai telegram https://my.telegram.org/apps

**Comment by shamhi** [comment]
> RANDOM_TAPS_COUNT=[50, 200]

this won't work, you need to set value in this format: 50,200

**Comment by EziiPz** [comment]
@shamhi can u give specific python version?

**Comment by EziiPz** [comment]
or link download

**Comment by EziiPz** [comment]
always same error 
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

**Comment by shamhi** [comment]
> always same error ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

https://stackoverflow.com/questions/76650856/no-module-named-pydantic-core-pydantic-core-in-aws-lambda-though-library-is-i

problem isn't in python version, try this solution

**Comment by valini98** [comment]
> always same error ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

try python 3.9,  im using python 3.9 bot work perfectly no error and running 1day

**Comment by EziiPz** [comment]
i already set 50,200 still got error

**Comment by valini98** [comment]
> > > always same error ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'
> > 
> > 
> > try python 3.9, im using python 3.9 bot work perfectly no error and running 1day
> 
> working but still got this error pydantic_settings.sources.SettingsError: error parsing value for field "RANDOM_TAPS_COUNT" from source "DotEnvSettingsSource"

im just input app id & app hash, usedefault setting

**Comment by EziiPz** [comment]
> im just input app id & app hash, usedefault setting
yeah working but now my number phone getting ban

**Comment by EziiPz** [comment]
my number get banned after using the bot can someone expain?

**Comment by shamhi** [comment]
> my number get banned after using the bot can someone expain?

in telegram or memefi?

**Comment by Buranbaev228** [comment]
help python 3.10, windows
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "c:\Users\Arslan\Desktop\HamsterKombatBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "c:\Users\Arslan\Desktop\HamsterKombatBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "c:\Users\Arslan\Desktop\HamsterKombatBot\bot\utils\launcher.py", line 10, in <module>
    from better_proxy import Proxy
  File "C:\Users\Arslan\AppData\Local\Programs\Python\Python310\lib\site-packages\better_proxy\__init__.py", line 1, in <module>    
    from .proxy import Proxy
  File "C:\Users\Arslan\AppData\Local\Programs\Python\Python310\lib\site-packages\better_proxy\proxy.py", line 5, in <module>       
    from pydantic import BaseModel
  File "C:\Users\Arslan\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\__init__.py", line 383, in __getattr__   
    module = import_module(module_name, package=package)
  File "C:\Users\Arslan\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Arslan\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 12, in <module>
    import pydantic_core
  File "C:\Users\Arslan\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic_core\__init__.py", line 6, in <module>   
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

**Comment by shamhi** [comment]
no, you have python 3.12+
