### ISSUE TITLE
error(solved)

### ISSUE THREAD

**Issue by Raindess69** [shamhi/MemeFiBot#10]
![image](https://github.com/shamhi/MemeFiBot/assets/165594530/aee2c44d-a83b-491c-8f4f-8eec904d62af)

такая ошибка с codespaces и на компе с питоном 3.10

**Comment by shamhi** [comment]
положил свои API_ID и API_HASH в файл .env?

**Comment by Raindess69** [comment]
> положил свои API_ID и API_HASH в файл .env?

разобрался, спасибо все ворк
