### ISSUE TITLE
To Fast and Cause Aplication Error

### ISSUE THREAD

**Issue by arifintajul4** [shamhi/MemeFiBot#12]
only run 1 hours
![image](https://github.com/shamhi/MemeFiBot/assets/36062540/d91329f2-ceb4-4b5d-890f-640d7f58529d)
and then when access bot, error like this
![image](https://github.com/shamhi/MemeFiBot/assets/36062540/f57b7619-2a1a-4447-80c5-f0d841afdb6b)

**Comment by 0zyyy** [comment]
Can we still run the bot even though the client-side has the error?

> See [this](https://github.com/shamhi/MemeFiBot/issues/6#issuecomment-2029637564). This is not a bot problem. I've been using it for several days now, until I reached level 5, everything works fine.

Can we still run the bot even though the client has that error?

**Comment by Alexell** [comment]
Oh, I don't know this.

**Comment by arifintajul4** [comment]
> See [this](https://github.com/shamhi/MemeFiBot/issues/6#issuecomment-2029637564). This is not a bot problem. I've been using it for several days now, until I reached level 5, everything works fine.

the issue is in level 5? not because bot to fast reach level 5?
in my computer, only need 1 hours to reach level 5

**Comment by Alexell** [comment]
The MemeFi Coin developers have already added a level 6 boss, so now this problem should only occur when you take away all of his hp.

**Comment by arifintajul4** [comment]
already fix, tq

**Comment by Ohonovskiy** [comment]
how many ADD CLICKS ON BOOST you have? 24mil is alot
