### ISSUE TITLE
Как запускать это все?

### ISSUE THREAD

**Issue by dezdemxn** [shamhi/MemeFiBot#14]
Хочется увидеть видео как запустить ваших ботов, не могу разобраться, заранее спасибо.

**Comment by shamhi** [comment]
в README есть пошаговая инструкция

**Comment by dezdemxn** [comment]
> в README есть пошаговая инструкция

я не обладаю знаниями с питоном и прочим, я установил его, пришел к тому что нужно открыть папку в терминале с ботом, и после ввода второй строчки виндовс возникает такая проблема.
![image](https://github.com/shamhi/MemeFiBot/assets/165968275/f9059eab-65be-4cf5-b6f1-3db198b4479c)

**Comment by shamhi** [comment]
открой эту папку в проводнике и посмотри, есть ли там папка venv

**Comment by dezdemxn** [comment]
Эта папка так называется, нету папки venv, все смотрел

**Comment by shamhi** [comment]
если ты выполнил `python -m venv venv` и ошибки не было, то она не может не создаться

**Comment by dezdemxn** [comment]
Что нужно иметь на компьютере кроме питона?

**Comment by shamhi** [comment]
какой версии питон?

**Comment by dezdemxn** [comment]
3.11.9 amd64
