### ISSUE TITLE
SSl как решить на дедике?

### ISSUE THREAD

**Issue by ATAMAH161** [shamhi/MemeFiBot#144]
![изображение_2024-09-06_162906651](https://github.com/user-attachments/assets/b816fb16-8f1f-4889-9ea7-fdca91799408)
Вот такая проблема. Тестил на ноутбуке всё работает, а вот на дедике выдаёт такое, как это решается?

**Comment by mirage2812** [comment]
поменяй прокси

**Comment by ATAMAH161** [comment]
Поменял дедик всё заработало. Взял с гео в Москве
