### ISSUE TITLE
+0

### ISSUE THREAD

**Issue by liluglymane666** [shamhi/MemeFiBot#19]
+0 через несколько часов после запуска.с прокси и без результат одинаковый.удалял файлы в pycache.ничего не помогает
![image](https://github.com/shamhi/MemeFiBot/assets/57453873/7c1a7aa5-79d5-4101-bf1f-8833121aa5d0)

**Comment by liluglymane666** [comment]
> да у них API кривой поставь в env у всех AUTO_UPGRADE_ значение False и проверь

не,не помогает

**Comment by khanh8910** [comment]
I think having 0 as a balance is normal because the balance doesn't increase after tapping if the number of points you tapped is higher than your energy cap.

**Comment by liluglymane666** [comment]
> да у них API кривой поставь в env у всех AUTO_UPGRADE_ значение False и проверь

Александр.не мог ли ты,пожалуйста, получить bearer token проекта Blum?У меня не совсем получается,а ты быстро справился,я думаю.Спасибо
