### ISSUE TITLE
ERROR 113, 132 and 373

### ISSUE THREAD

**Issue by Bloody9112** [shamhi/MemeFiBot#21]
[
<img width="682" alt="Знімок екрана 2024-04-19 о 21 11 53" src="https://github.com/shamhi/MemeFiBot/assets/57665482/94de9ea3-f1bc-4901-85ce-7106e98064e9">
](url)

**Comment by quitzal** [comment]
Same problem, did you solve it?

**Comment by wushatneen** [comment]
Вероятнее всего у вас сбилось время, поставьте автонастройку времени по вашему часовому поясу

**Comment by threesolaris** [comment]
![Screenshot_1](https://github.com/shamhi/MemeFiBot/assets/119353906/f43f76af-ab3e-4d46-b876-a62f2db4f4d1)
Может быть из-за того, что две сессии одновременно висят?

**Comment by shamhi** [comment]
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
