### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by whatever193** [shamhi/MemeFiBot#4]
Hi, How can i add proxy?

**Comment by shamhi** [comment]
bot don't work? why you need proxy?

**Comment by whatever193** [comment]
> bot don't work? why you need proxy?
I want run two account on my computer. Does it matter if I don't use a proxy?

**Comment by shamhi** [comment]
> > bot don't work? why you need proxy?
> > I want run two account on my computer. Does it matter if I don't use a proxy?

it will be work without proxy

**Comment by shamhi** [comment]
okay, I'll add this feature
