### ISSUE TITLE
i run bot 15 hours ago, in lvl 11 in two acounts(all in bot 3 accounts), and now i cannot do anyting in this account boss 11 lvl died but new(12lvl) not started

### ISSUE THREAD

**Issue by gmixaOI** [shamhi/MemeFiBot#43]
![Untitled](https://github.com/shamhi/MemeFiBot/assets/2504935/2791555f-6bff-4aba-a834-836ddc82a5fc)
in console i see this, i reboot bot but not change...,
i run app in mobile and in two accounts this....
![Untitled1](https://github.com/shamhi/MemeFiBot/assets/2504935/6c22e8d0-65e5-49ed-a5d1-2c7d79a81531)
![Untitled2](https://github.com/shamhi/MemeFiBot/assets/2504935/6dcba327-e146-41e6-b767-dc135321adca)
press key "continue playing" not do anything...

**Comment by gmixaOI** [comment]
12 lvl not isset in game(from chat memefi)

**Comment by McRoyce** [comment]
Have you resolved the problem?
Is there a way to go back to fighting the level 1 boss?

**Comment by gmixaOI** [comment]
> Have you resolved the problem? Is there a way to go back to fighting the level 1 boss?

11 level is latest level in game.. this is not bug)
