### ISSUE TITLE
Please Fix This Error

### ISSUE THREAD

**Issue by Pawansingh333** [shamhi/MemeFiBot#49]
![Memefi](https://github.com/shamhi/MemeFiBot/assets/167502767/d1a627c7-3bc5-4b2e-b6b3-7f9800ca836d)

**Comment by shamhi** [comment]
it's means that you need proxies

**Comment by Pawansingh333** [comment]
shamhi thanks for replying  but Where can I get a free SOCKS5 proxy with a username and password?
