### ISSUE TITLE
The number of accounts in the virtual server

### ISSUE THREAD

**Issue by MGTV01** [shamhi/MemeFiBot#54]
It is very good. How many user accounts can be used in a virtual server??? Is there a limit? I am currently using one user account, but I want to add more accounts. What is the solution?

**Comment by NLegal** [comment]
все зависит от конфигураций
у меня 10 аккаунтов бежит на каждом из ботов на одной системе. нагрузка нулевая, траффик тоже.
самая большая проблема это будет мониторить и перезагружать отвалившихся

**Comment by MGTV01** [comment]
> همه وابسته به تنظیمات مربوط به 10 مورد است. нагрузка нулевая, траффик тоже. ساмая большая مشکل این خواهد بود مانیتوریتь و پخش отвалившихся

Very good. Is it possible to keep the window open with the screen? I want to implement all the existing bots on one server. Will I have a problem???

**Comment by NLegal** [comment]
sure.
1 way:
1 bot manages all accounts, create or add your sessions under "sessions" folder.
start the bot, it would detect sessions and would run your sessions.
One issue I experienced, is that if you use same API key, it might give weird behaviors.
2 way:
create copies of your bot, each one has its own API key, session.
this way each account runs independently.

test it out, find whats better works for you.

**Comment by MGTV01** [comment]
> مطمئن. 1 راه: 1 ربات تمام حساب ها را مدیریت می کند، جلسات خود را در پوشه "sessions" ایجاد یا اضافه می کند. ربات را راه اندازی کنید، جلسات را شناسایی می کند و جلسات شما را اجرا می کند. یکی از مشکلاتی که من تجربه کردم، این است که اگر از همان کلید API استفاده کنید، ممکن است رفتارهای عجیب و غریبی ایجاد کند. راه دوم: کپی هایی از ربات خود ایجاد کنید، هر کدام کلید API، جلسه خود را دارند. به این ترتیب هر حساب به طور مستقل اجرا می شود.
> 
> آن را امتحان کنید، پیدا کنید چه چیزی برای شما بهتر است.

Thank you very much my friend. I will do it

**Comment by MGTV01** [comment]
> مطمئن. 1 راه: 1 ربات تمام حساب ها را مدیریت می کند، جلسات خود را در پوشه "sessions" ایجاد یا اضافه می کند. ربات را راه اندازی کنید، جلسات را شناسایی می کند و جلسات شما را اجرا می کند. یکی از مشکلاتی که من تجربه کردم، این است که اگر از همان کلید API استفاده کنید، ممکن است رفتارهای عجیب و غریبی ایجاد کند. راه دوم: کپی هایی از ربات خود ایجاد کنید، هر کدام کلید API، جلسه خود را دارند. به این ترتیب هر حساب به طور مستقل اجرا می شود.
> 
> آن را امتحان کنید، پیدا کنید چه چیزی برای شما بهتر اس
