### ISSUE TITLE
I stopped at the 3rd boss, it shows charge upgraded to 4 lvl and doesn’t go further

### ISSUE THREAD

**Issue by Blasthacker** [shamhi/MemeFiBot#58]
What to do?
![ыФЫфыфыЫыфФФЫЫы](https://github.com/shamhi/MemeFiBot/assets/171959503/fae8ab09-0a8e-4953-895d-685604268dfa)

**Comment by Pasha4056** [comment]
Disable automatic charge upgrade in the .env file

**Comment by Blasthacker** [comment]
thank you
