### ISSUE TITLE
Unknown error while getting Access Token

### ISSUE THREAD

**Issue by mrdarkerr** [shamhi/MemeFiBot#74]
MemeFiBot | 2024-06-17 15:36:30 | ERROR    | 113 - m2 | Unknown error while getting Access Token: 429, message='Too Many Requests', url=URL('https://api-gw-tg.memefi.club/graphql')

**Comment by mrdarkerr** [comment]
Any Tip!?

**Comment by mironov1338** [comment]
Your account is locked in the block, wait 24 hours and everything will be unlocked.
The creators decided to work on farms!
You can check the lock if you try to buy pumping, if it works, then the block is removed, as well as manually tap and refresh the page, if there is full energy again, then the lock is not lifted!

**Comment by Freddywhest** [comment]
> Your account is locked in the block, wait 24 hours and everything will be unlocked. The creators decided to work on farms! You can check the lock if you try to buy pumping, if it works, then the block is removed, as well as manually tap and refresh the page, if there is full energy again, then the lock is not lifted!



> Your account is locked in the block, wait 24 hours and everything will be unlocked. The creators decided to work on farms! You can check the lock if you try to buy pumping, if it works, then the block is removed, as well as manually tap and refresh the page, if there is full energy again, then the lock is not lifted!



> Your account is locked in the block, wait 24 hours and everything will be unlocked. The creators decided to work on farms! You can check the lock if you try to buy pumping, if it works, then the block is removed, as well as manually tap and refresh the page, if there is full energy again, then the lock is not lifted!

Using this does not block your account https://github.com/Freddywhest/MemeFiBot

**Comment by mrdarkerr** [comment]
.env  --->   SLEEP_BETWEEN_TAP= [38, 40]
