### ISSUE TITLE
Please Sir :(

### ISSUE THREAD

**Issue by fiqi732** [shamhi/MemeFiBot#93]
![Screenshot (11)](https://github.com/shamhi/MemeFiBot/assets/168587624/44a037a6-7539-4e31-ae69-3dc05920ae30)

**Comment by mironov1338** [comment]
Your account is locked in the block, wait 24 hours and everything will be unlocked.
The creators decided to work on farms!
You can check the lock if you try to buy pumping, if it works, then the block is removed, as well as manually tap and refresh the page, if there is full energy again, then the lock is not lifted!

**Comment by fiqi732** [comment]
@mironov1338 thankyou your information sir
